require('datsudo.keymaps')
require('datsudo.plugins')
require('datsudo.colorscheme')
require('datsudo.cmp')
require('datsudo.lsp')
require("datsudo.telescope")
require("datsudo.treesitter")
require("datsudo.comment")
require("datsudo.nvim-tree")
require('datsudo.options')
require("datsudo.bufferline")
require("datsudo.lualine")
require("datsudo.toggleterm")
require("datsudo.workspaces")
require("datsudo.code-runner")
require("datsudo.alpha-nvim")

